const quesarr = [
  { q: "Do you have itching?" },
  { q: "Do you have skin rash?" },
  { q: "Do you have nodal skin eruptions?" },
  { q: "Do you have continuous sneezing?" },
  { q: "Do you have shivering?" },
  { q: "Do you have chills?" },
  { q: "Do you have joint pain?" },
  { q: "Do you have stomach pain?" },
  { q: "Do you have acidity?" },
  { q: "Do you have ulcers on tongue?" },
  { q: "Do you have muscle wasting?" },
  { q: "Do you have vomiting?" },
  { q: "Do you have burning micturition?" },
  { q: "Do you have spotting  urination?" },
  { q: "Do you have fatigue?" },
  { q: "Do you have weight gain?" },
  { q: "Do you have anxiety?" },
  { q: "Do you have cold hands and feets?" },
  { q: "Do you have mood swings?" },
  { q: "Do you have weight loss?" },
  { q: "Do you have restlessness?" },
  { q: "Do you have lethargy?" },
  { q: "Do you have patches in throat?" },
  { q: "Do you have irregular sugar level?" },
  { q: "Do you have cough?" },
  { q: "Do you have high fever?" },
  { q: "Do you have sunken eyes?" },
  { q: "Do you have breathlessness?" },
  { q: "Do you have sweating?" },
  { q: "Do you have dehydration?" },
  { q: "Do you have indigestion?" },
  { q: "Do you have headache?" },
  { q: "Do you have yellowish skin?" },
  { q: "Do you have dark urine?" },
  { q: "Do you have nausea?" },
  { q: "Do you have loss of appetite?" },
  { q: "Do you have pain behind the eyes?" },
  { q: "Do you have back pain?" },
  { q: "Do you have constipation?" },
  { q: "Do you have abdominal pain?" },
  { q: "Do you have diarrhoea?" },
  { q: "Do you have mild fever?" },
  { q: "Do you have yellow urine?" },
  { q: "Do you have yellowing of eyes?" },
  { q: "Do you have acute liver failure?" },
  { q: "Do you have fluid overload?" },
  { q: "Do you have swelling of stomach?" },
  { q: "Do you have swelled lymph nodes?" },
  { q: "Do you have malaise?" },
  { q: "Do you have blurred and distorted vision?" },
  { q: "Do you have phlegm?" },
  { q: "Do you have throat irritation?" },
  { q: "Do you have redness of eyes?" },
  { q: "Do you have sinus pressure?" },
  { q: "Do you have runny nose?" },
  { q: "Do you have congestion?" },
  { q: "Do you have chest pain?" },
  { q: "Do you have weakness in limbs?" },
  { q: "Do you have fast heart rate?" },
  { q: "Do you have pain during bowel movements?" },
  { q: "Do you have pain in anal region?" },
  { q: "Do you have bloody stool?" },
  { q: "Do you have irritation in anus?" },
  { q: "Do you have neck pain?" },
  { q: "Do you have dizziness?" },
  { q: "Do you have cramps?" },
  { q: "Do you have bruising?" },
  { q: "Do you have obesity?" },
  { q: "Do you have swollen legs?" },
  { q: "Do you have swollen blood vessels?" },
  { q: "Do you have puffy face and eyes?" },
  { q: "Do you have enlarged thyroid?" },
  { q: "Do you have brittle nails?" },
  { q: "Do you have swollen extremeties?" },
  { q: "Do you have excessive hunger?" },
  { q: "Do you have extra marital contacts?" },
  { q: "Do you have drying and tingling lips?" },
  { q: "Do you have slurred speech?" },
  { q: "Do you have knee pain?" },
  { q: "Do you have hip joint pain?" },
  { q: "Do you have muscle weakness?" },
  { q: "Do you have stiff neck?" },
  { q: "Do you have swelling joints?" },
  { q: "Do you have movement stiffness?" },
  { q: "Do you have spinning movements?" },
  { q: "Do you have loss of balance?" },
  { q: "Do you have unsteadiness?" },
  { q: "Do you have weakness of one body side?" },
  { q: "Do you have loss of smell?" },
  { q: "Do you have bladder discomfort?" },
  { q: "Do you have foul smell of urine?" },
  { q: "Do you have continuous feel of urine?" },
  { q: "Do you have passage of gases?" },
  { q: "Do you have internal itching?" },
  { q: "Do you have toxic look (typhos)?" },
  { q: "Do you have depression?" },
  { q: "Do you have irritability?" },
  { q: "Do you have muscle pain?" },
  { q: "Do you have altered sensorium?" },
  { q: "Do you have red spots over body?" },
  { q: "Do you have belly pain?" },
  { q: "Do you have abnormal menstruation?" },
  { q: "Do you have dischromic  patches?" },
  { q: "Do you have watering from eyes?" },
  { q: "Do you have increased appetite?" },
  { q: "Do you have polyuria?" },
  { q: "Do you have family history?" },
  { q: "Do you have mucoid sputum?" },
  { q: "Do you have rusty sputum?" },
  { q: "Do you have lack of concentration?" },
  { q: "Do you have visual disturbances?" },
  { q: "Do you have receiving blood transfusion?" },
  { q: "Do you have receiving unsterile injections?" },
  { q: "Do you have coma?" },
  { q: "Do you have stomach bleeding?" },
  { q: "Do you have distention of abdomen?" },
  { q: "Do you have history of alcohol consumption?" },
  { q: "Do you have fluid overload.1?" },
  { q: "Do you have blood in sputum?" },
  { q: "Do you have prominent veins on calf?" },
  { q: "Do you have palpitations?" },
  { q: "Do you have painful walking?" },
  { q: "Do you have pus filled pimples?" },
  { q: "Do you have blackheads?" },
  { q: "Do you have scurring?" },
  { q: "Do you have skin peeling?" },
  { q: "Do you have silver like dusting?" },
  { q: "Do you have small dents in nails?" },
  { q: "Do you have inflammatory nails?" },
  { q: "Do you have blister?" },
  { q: "Do you have red sore around nose?" },
  { q: "Do you have yellow crust ooze?" },
  { q: "Do you have prognosis?" }
];

export default quesarr;
